# Xpath
url = 'https://qauto2.forstudy.space/'
# 0 = r'//*[@class="container"]'
# 1 = r'//*[@class="container"]/div'
# 2 = r'//*[@class="container"]/div/div'
# 3 = r'//*[@class="container"]/div/div/*'
# 4 = r'//*[@class="container"]/..'
# 5 = r'//*[@class="container"]/../../*'
# 6 = r'//*[@class="container"]//*'
# 7 = r'//*[@class="container"]//a[@class="header_logo"]'
# 8 = r'//*[@class="container"]//a[@class="header_logo"]//*[local-name()="svg"]'
# 9 = r'//*[@class="container"]/parent::header[@class="header bg-basic-dark"]'
# 10 = r'//*[@class="container"]//nav[@class="header_nav d-flex align-items-center"]'
# 11 = r'//app-root[@ng-version="11.0.8"]//a[@class="header_logo"]'
# 12 = r'//app-root[@ng-version="11.0.8"]//a[@class="header_logo"]/following-sibling::nav[@class="header_nav d-flex align-items-center"]'
# 13 = r'//app-root[@ng-version="11.0.8"]//footer[@class="footer d-flex align-items-center"]'
# 14 = r'//nav[@class="header_nav d-flex align-items-center"]/../../div[@class="header_left d-flex align-items-center"]'
# 15 = r'//nav[@class="header_nav d-flex align-items-center"]/../../div[@class="header_left d-flex align-items-center"]/following-sibling::div[@class="header_right d-flex align-items-center"]'
# 16 = r'//app-root[@ng-version="11.0.8"]/ancestor::body'
# 17 = r'//body//app-alert-list/../div[@class="app-wrapper"]'
# 18 = r'//app-footer/footer[@class="footer d-flex align-items-center"]/../../div[@class="app-wrapper"]'
# 19 = r'//header[@class="header bg-basic-dark"]/ancestor::body/preceding-sibling::head'
# 20 = r'(//div[@class="container"])[1]'
# 21 = r'//div[@class="container"]/../../following-sibling::div[@class="app-content"]'

url = 'https://qauto2.forstudy.space/panel/garage'
# 22 = r'//app-root/app-global-layout//header[@class="header bg-basic-dark"]//div[@class="header_inner d-flex justify-content-between align-items-center"]'
# 23 = r'//app-root/app-global-layout//header[@class="header bg-basic-dark"]//div[@class="header_inner d-flex justify-content-between align-items-center"]/ancestor::div[@class="global-layout"]'
# 24 = r'//a[text()="Fuel expenses"][@class="btn header-link -active"]'
# 25 = r'//a[text()="Fuel expenses" and @class="btn header-link -active"]/../../following-sibling::app-user-nav/..//button[text()=" My profile "]'
#


# css
url = 'https://qauto2.forstudy.space/'
# 1 = r'div.container'
# 2 = r'div.container a.header_logo'
# 3 = r'div.container > div.header_inner.d-flex.justify-content-between.align-items-center'
# 4 = r'div.container div.header_left.d-flex.align-items-center + div.header_right.d-flex.align-items-center'
# 5 = r'div.container div.header_left.d-flex.align-items-center+div>.header-link.-guest'
# 6 = r'div.container div.header_left.d-flex.align-items-center+div>.header-link.-guest~button'
# 7 = r'div.global-layout path[d="M60.75 29.25V8.39442C60.75 6.41744 61.2134 5.49006 62.586 4.71802C63.436 4.25136 64.0592 3.9638 64.3566 3.80939L64.5 3.73438V29.25H60.75Z"]'
# 8 = r'div.global-layout app-header > header'
# 9 = r'div.global-layout app-header ~ div.app-content div.col-12.col-lg-4 > div > h1[class="hero-descriptor_title display-2"] + p'
# 10 = r'div.global-layout app-header ~ div.app-content div.col-12.col-lg-4'
# 11 = r'head > title ~ script:nth-of-type(8)'
# 12 = r'body p.hero-descriptor_descr.lead'
# 13 = r'body app-footer > footer div.row.d-flex.flex-column.flex-md-row.align-items-center'
# 14 = r'style[name="www-roboto"]'
# 15 = r'section iframe'
# 16 = r'div.global-layout app-header ~ div.app-content div.col-12.col-lg-4 > div'
# 17 = r'head > title ~ style[type="text/css"]'
# 18 = r'div.container path:nth-of-type(10)'
# 19 = r'body app-footer > footer div.row.d-flex.flex-column.flex-md-row.align-items-center p:nth-of-type(2)'
# 20 = r'html > head link[href="/s/player/ab89db3f/www-player.css"]'
# 21 = r'div.global-layout app-header ~ div.app-content'
# 22 = r'app-guest-layout button'
# 23 = r'head > title ~ base'
# 24 = r'div.global-layout app-header ~ div.app-content div.col-12.col-lg-4 > div > h1[class="hero-descriptor_title display-2"]'
# 25 = r'body app-footer > footer'

